import 'element-plus/es/components/loading/style/css'
import 'element-plus/es/components/progress/style/css'
import '@muyianking/theme-chalk/css/upload.css'
import '../../preview/style/index'
import '../../icon/style/index'
